// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Api struct {
	ID           int32
	UserID       pgtype.Int4
	Name         string
	IsActive     pgtype.Bool
	ClientID     string
	ClientSecret string
}

type Epoch struct {
	ID         int32
	TrainRunID pgtype.Int4
	EpochNo    int32
	Type       pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Metric struct {
	EpochID int32
	Key     string
	Value   float64
}

type Model struct {
	ID          int32
	UserID      pgtype.Int4
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ModelVersion struct {
	ID        int32
	ModelID   pgtype.Int4
	Version   string
	Path      pgtype.Text
	Config    []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TrainRun struct {
	ID              int32
	ModelVersionID  pgtype.Int4
	RunName         pgtype.Text
	Hyperparameters []byte
	StartedAt       pgtype.Timestamp
	FinishedAt      pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
