// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Api struct {
	ID       pgtype.UUID
	Name     string
	IsActive pgtype.Bool
	Apikey   string
	UserID   pgtype.UUID
}

type Epoch struct {
	ID         pgtype.UUID
	EpochNo    int32
	Type       pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	TrainRunID pgtype.UUID
}

type Metric struct {
	EpochID pgtype.UUID
	Key     string
	Value   float64
}

type Model struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	UserID      pgtype.UUID
}

type ModelVersion struct {
	ID        pgtype.UUID
	Version   string
	Path      pgtype.Text
	Config    []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	ModelID   pgtype.UUID
}

type Session struct {
	ID           pgtype.UUID
	Sessiontoken string
	Refreshtoken string
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	UserID       pgtype.UUID
}

type TrainRun struct {
	ID              pgtype.UUID
	RunName         pgtype.Text
	Hyperparameters []byte
	StartedAt       pgtype.Timestamp
	FinishedAt      pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ModelVersionID  pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
